version: "3.8"

services:
<<<<<<< HEAD
  www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php82
    ports:
      - "8000:80"
=======
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tmdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
>>>>>>> origin/flo
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"

  web:
    image: php:7.4-apache
    volumes:
      - ./html:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

<<<<<<< HEAD
  db:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: demo
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"

  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 20M
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: test
      PMA_PASSWORD: pass

    ports:
      - 8899:80
=======
volumes:
  db-data:
>>>>>>> origin/flo
